Start shipyard phase forw v0.9.0-m2
submariner-io/releases pull request #106
Opened 2021-03-31 07:05 UTC by mangelajo

2021-03-31 08:18 UTC, skitt requested changes

2021-03-31 08:18 UTC, skitt commented on releases/v0.9.0-m2.yaml
> +
The blank line here trips up `yamllint`.

2021-03-31 08:19 UTC, skitt commented
Oh, apparently dropping the git-tagged images has broken the release e2e...

2021-03-31 08:45 UTC, mangelajo commented
> Oh, apparently dropping the git-tagged images has broken the release e2e...

oh did we drop git-tagged images? :?

2021-03-31 08:45 UTC, mangelajo commented
> Oh, apparently dropping the git-tagged images has broken the release e2e...

we need them back

2021-03-31 09:24 UTC, mangelajo commented on releases/v0.9.0-m2.yaml
> +
Done

2021-03-31 09:26 UTC, mangelajo commented
> > Oh, apparently dropping the git-tagged images has broken the release e2e...
> 
> we need them back

We actually had them, just the image name had changed :)

2021-03-31 09:26 UTC, skitt approved these changes

2021-03-31 11:49 UTC, tpantelis approved these changes

2021-03-31 12:21 UTC, mkolesnik commented
Seems theres some trouble building the subctl binary, some sneaky `w` is sneaking in somehow..

From the E2E log:
```
[submariner-operator]$ make --debug=b bin/subctl w --debug=b -- using=
```

This happens inside the dapper, but outside the call is simply `make bin/subctl`

2021-03-31 17:06 UTC, mangelajo commented
E2E needs rerun after the new shipyard images generate. https://www.nytimes.com/2021/03/31/technology/turing-award-aho-ullman.html

2021-03-31 21:29 UTC, tpantelis commented
E2E is failing.  @mkolesnik can you look into this please?

2021-04-01 08:35 UTC, mkolesnik commented
> E2E is failing. @mkolesnik can you look into this please?

So there's been a regression https://github.com/submariner-io/submariner-operator/issues/1209
I've created #109 which should fix it here

2021-04-05 12:43 UTC, mkolesnik commented
Seems we also need #110 though I'm not sure why it didnt interfere before

2021-04-06 08:27 UTC, merged