Advancing 0.20.0-m2 release to status: installers
submariner-io/releases pull request #1173
Opened 2024-12-23 11:23 UTC by prachiyadav

Components:
* https://github.com/submariner-io/admiral/commits/devel
* https://github.com/submariner-io/cloud-prepare/commits/devel
* https://github.com/submariner-io/lighthouse/commits/devel
* https://github.com/submariner-io/shipyard/commits/devel
* https://github.com/submariner-io/submariner/commits/devel
* https://github.com/submariner-io/submariner-operator/commits/devel
Depends on https://github.com/submariner-io/submariner-operator/pull/3305

2024-12-23 11:25 UTC, maayanf24 approved these changes

2024-12-23 12:10 UTC, yboaron approved these changes

2025-01-02 08:34 UTC, skitt approved these changes

2025-01-02 08:36 UTC, skitt requested changes
The operator hash will need to be updated once the bump PR is merged.

2025-01-06 17:13 UTC, closed without merging