Update example to v0.6.0
submariner-io/releases pull request #22
Opened 2020-09-22 07:16 UTC by mkolesnik

This should fix E2E

Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>

2020-09-22 08:00 UTC, mangelajo commented
@mkolesnik cool checks: ERROR: Expected Shipyard version 0.6.0 but found 0.6.1 in lighthouse (releases/example.yaml)  may be we should go with v0.6.1 which was the final?

https://github.com/submariner-io/lighthouse/blob/v0.6.1/Dockerfile.dapper

2020-09-22 12:08 UTC, dfarrell07 requested changes
```
ERROR: Expected Admiral version v0.6.1 but found v0.6.0 in lighthouse (releases/example.yaml)
ERROR: Expected Admiral version v0.6.1 but found v0.6.0 in submariner (releases/example.yaml)
ERROR: Expected Shipyard version 0.6.1 but found 0.6.0 in admiral (releases/example.yaml)
```

2020-10-12 10:17 UTC, mkolesnik commented
As we discussed on the automation sync call, this also disables the sync checks for Admiral & Shipyard for the time being

2020-10-13 13:57 UTC, mangelajo approved these changes

2020-10-13 17:05 UTC, tpantelis approved these changes

2020-10-13 17:09 UTC, merged