Stop using deprecated --service-discovery flag
submariner-io/releases pull request #271
Opened 2021-11-26 10:55 UTC by skitt

subctl deploy-broker's --service-discovery flag is deprecated and
about to be removed. Service discovery is now enabled by default, so
we no longer need to specify this anyway.

Signed-off-by: Stephen Kitt <skitt@redhat.com>

2021-11-26 12:56 UTC, tpantelis approved these changes

2021-11-28 07:38 UTC, maayanf24 approved these changes

2021-11-29 20:56 UTC, dfarrell07 approved these changes

2021-11-30 09:18 UTC, mkolesnik requested changes

2021-11-30 09:18 UTC, mkolesnik commented on Makefile
> -override DEPLOY_ARGS += $(CLUSTER_SETTINGS_FLAG) --deploytool_broker_args '--service-discovery'
We still require the settings flag though

2021-12-08 10:01 UTC, mkolesnik approved these changes

2021-12-08 10:02 UTC, merged