Use `git clone` to clone the repo
submariner-io/releases pull request #32
Opened 2020-10-15 13:41 UTC by mkolesnik

This allows us to use full commit ids, short hashes and tags for the
components, and also allows us to fetch the correct image by calculating
the image version from the commit itself (in case its not a tag).

This should allow us to use `gh release` with short commit ids (which it
doesnt support) (Enables #28)

Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>

2020-10-15 13:49 UTC, skitt requested changes
`git -C` to the rescue!

2020-10-15 13:49 UTC, skitt commented on scripts/lib/utils
> +        popd
```suggestion
        git -C "projects/${project}" fetch -v --tags
```

2020-10-15 13:49 UTC, skitt commented on scripts/lib/utils
> +        popd
```suggestion
        git clone "https://github.com/submariner-io/${project}" "projects/${project}"
```

2020-10-15 13:49 UTC, skitt commented on scripts/lib/utils
> +    popd
```suggestion
    git -C "projects/${project}" checkout "${release["components.${project}"]}"
```

2020-10-15 13:49 UTC, skitt commented on scripts/images.sh
> +                popd
```suggestion
                local project_version=$(git -C "projects/${project}" describe --tags --dirty="-${DEV_VERSION}" --exclude="${CUTTING_EDGE}" --exclude="latest")
                _pull_image "$project_version"
```

2020-10-19 06:01 UTC, mkolesnik commented on scripts/images.sh
> +                popd
Thanks, I'll add it as a function :)

2020-10-19 06:02 UTC, mkolesnik commented
> `git -C` to the rescue!

Cool didn't know about it, thanks!

I'll add it as a function

2020-10-19 07:43 UTC, skitt approved these changes

2020-10-19 08:02 UTC, dfarrell07 approved these changes

2020-10-19 11:07 UTC, merged