Add `installers` stage to the release process
submariner-io/releases pull request #361
Opened 2022-05-19 12:01 UTC by mkolesnik

Add `installers` stage before `released` as now `subctl` lives in its
own repository and hence would be the last thing released.
Hence, the installers (charts and operator) need to be released before
`subctl`.

Resolves #340 

Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>

2022-05-19 14:53 UTC, tpantelis commented on scripts/lib/utils
>  readonly OPERATOR_CONSUMES=(submariner cloud-prepare lighthouse)
**submariner-operator** no longer used **cloud-prepare**.

2022-05-25 12:26 UTC, tpantelis approved these changes

2022-05-25 12:57 UTC, skitt requested changes
Minor tweak to avoid a shellcheck override.

2022-05-25 12:57 UTC, skitt commented on scripts/do-release.sh
> +    release_${release['status']}
This *should* work here:

```suggestion
    "release_${release['status']}"
```

2022-05-25 13:13 UTC, skitt approved these changes

2022-05-25 13:33 UTC, tpantelis commented
What about building releases of versions prior to the `subctl` repo refactor? It seems we need to keep the prior behavior in that case.

2022-05-25 13:36 UTC, mkolesnik commented
> What about building releases of versions prior to the `subctl` repo refactor? It seems we need to keep the prior behavior in that case.

You;re right, but that would be quite problematic with the existing code to support two split build routes.
We should probably create a stable branch for pre-0.13 builds and handle them there (not great but at least would work).

2022-05-25 14:08 UTC, tpantelis commented
> > What about building releases of versions prior to the `subctl` repo refactor? It seems we need to keep the prior behavior in that case.
> 
> You;re right, but that would be quite problematic with the existing code to support two split build routes. We should probably create a stable branch for pre-0.13 builds and handle them there (not great but at least would work).

yeah that sounds reasonable. Realistically it will probably be just one more 0.12 release that we'll have to build anyway.

2022-05-28 14:02 UTC, tpantelis commented
> > > What about building releases of versions prior to the `subctl` repo refactor? It seems we need to keep the prior behavior in that case.
> > 
> > 
> > You;re right, but that would be quite problematic with the existing code to support two split build routes. We should probably create a stable branch for pre-0.13 builds and handle them there (not great but at least would work).
> 
> yeah that sounds reasonable. Realistically it will probably be just one more 0.12 release that we'll have to build anyway.

OK - I created a [pre-0.13 branch](https://github.com/submariner-io/releases/tree/pre-0.13/) using these commands:

```bash
  git checkout -B pre-0.13 remotes/upstream/devel
  git push upstream pre-0.13
```

If it looks good we should be able to merge this. cc @skitt

2022-05-30 08:05 UTC, mkolesnik commented
> OK - I created a [pre-0.13 branch](https://github.com/submariner-io/releases/tree/pre-0.13/) using these commands:
> 
> ```shell
>   git checkout -B pre-0.13 remotes/upstream/devel
>   git push upstream pre-0.13
> ```
> 
> If it looks good we should be able to merge this. cc @skitt

I think we should follow same naming convention, so I created `release-0.12`

I based it on most recent 0.12 release commit, but not including any 0.13 (as it's not relevant for that branch).

I'll merge this one so I can start `0.13.0-m2` and if we need any adjustments we can of course make them later

2022-05-30 08:05 UTC, merged