Support branching on `releases` itself
submariner-io/releases pull request #366
Opened 2022-05-30 07:09 UTC by mkolesnik

In order to support releasing older stable releases while the release
process is diverging (due to adding images, repositories, etc), we need
to change the release model such that stable branch releases happen on
branches on `releases` itself.

Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>

2022-05-30 08:01 UTC, mkolesnik commented
This should be backported to `release-0.12` and any other stable branch we intend to support

2022-06-15 08:51 UTC, nyechiel commented
This breaks some of the releases testing. We can live without it for 0.12.2, but should merge before we tag 0.13.0-rc0.

2022-06-16 14:45 UTC, skitt requested changes

2022-06-16 14:45 UTC, skitt commented on Makefile
> +BASE_BRANCH = devel
Why are these changes needed? (This one and hard-coding `devel` in line 72.)

2022-06-21 12:06 UTC, mkolesnik commented
Seems that the branching out must happen on theCI, so closing this in favor of (much simpler) #391

2022-06-21 12:06 UTC, closed without merging