Use latest stable branch when testing
submariner-io/releases pull request #609
Opened 2022-12-21 10:22 UTC by mkolesnik

Instead of hard coding a branch, use the latest from the upstream remote.

Resolves #567 

Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>

2022-12-21 11:15 UTC, skitt requested changes

2022-12-21 11:15 UTC, skitt commented on scripts/test/release.sh
> +branch=$(git rev-parse --symbolic --remotes='submariner/release-*' | grep -o -m 1 'release-[0-9]*\.[0-9]*')
If you want the latest stable branch:

```suggestion
branch=$(git rev-parse --symbolic --remotes='submariner/release-*' | sort -rV | grep -o -m 1 'release-[0-9]*\.[0-9]*')
```

2023-01-02 15:25 UTC, skitt approved these changes

2023-01-02 15:28 UTC, tpantelis approved these changes

2023-01-02 15:35 UTC, merged