Use latest RC image as initial GA image
submariner-io/releases pull request #624
Opened 2023-01-10 15:17 UTC by mkolesnik

In case we're releasing the first GA, use the latest (RC) image which has been thoroughly validated during a test day, instead of relying on a rebuilt image which might've introduced unforeseen issues.

Depends on #617 

Resolves #335 

Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>

2023-01-11 17:31 UTC, skitt requested changes
Just a minor tweak.

2023-01-11 17:31 UTC, skitt commented on scripts/do-release.sh
> +        project_version=$(git rev-parse --symbolic --tags="v${semver[major]}.${semver[minor]}.*" | sort -V | tail -1)
```suggestion
        project_version=$(git rev-parse --symbolic --tags="v${semver[major]}.${semver[minor]}.*" | sort -V | tail -n1)
```

2023-01-16 13:43 UTC, skitt approved these changes

2023-01-29 10:08 UTC, maayanf24 approved these changes

2023-01-29 11:44 UTC, merged